export const SET_FLAG_TRUE = 'SET_FLAG_TRUE';
export const SET_FLAG_FALSE = 'SET_FLAG_FALSE';

export const SAVE_CLIENT_IN_DB = 'SAVE_CLIENT_IN_DB';
export const SAVE_ORIGIN_DESTINATION_IN_DB = 'SAVE_ORIGIN_DESTINATION_IN_DB';
export const SAVE_SUPPLIER_IN_DB = 'SAVE_SUPPLIER_IN_DB';
export const SAVE_PRODUCT_IN_DB = 'SAVE_PRODUCT_IN_DB';
export const SAVE_PRESENTATION_IN_DB = 'SAVE_PRESENTATION_IN_DB';
